ahrs:
  - /imu/data

gps:
  - /ublox/fix

lidar:
  - /points

ascender:
  - /ascender_position_estimation
  - /ascender_sensor_calib
  - /ascender_position_desired_control
  - /ascender_rope_length
  - /encoder_inc_left
  - /encoder_inc_right
  - /encoder_abs_left
  - /encoder_abs_right
  - /encoder_rs_left
  - /encoder_rs_right
  - /loadcell_left
  - /loadcell_right
  - /q21
  - /q22
  - /q21_dot
  - /q22_dot
  - /current_left
  - /current_right
  - /temperature_left
  - /temperature_right
  - /error_left
  - /error_right

zed2:
  - /zed2/zed_node/atm_press
  - /zed2/zed_node/depth/depth_registered
  - /zed2/zed_node/imu/data
  - /zed2/zed_node/odom
  - /zed2/zed_node/left/image_rect_color
  - /zed2/zed_node/right/image_rect_color
  - /zed2/zed_node/point_cloud/cloud_registered

zed2i:
  - /zed2i/zed_node/atm_press
  - /zed2i/zed_node/depth/depth_registered
  - /zed2i/zed_node/imu/data
  - /zed2i/zed_node/odom
  - /zed2i/zed_node/left/image_rect_color
  - /zed2i/zed_node/right/image_rect_color
  - /zed2i/zed_node/point_cloud/cloud_registered
