ahrs:
  - /imu/data

rtk_gps:
  - /ublox/fix
  - /ublox/vel

normal_gps:
  - /ascen/fix
  - /ascen/vel

lidar:
  - /points

ascender:
  - /ascender_position_estimation  # PoseStamped
  - /ascender_sensor_values
  - /ascender_sensor_values_filter
  - /ascender_rope_length
  - /wheelleg_joint_state_desired
  - /ascender_joint_state_desired
  - /wheelleg_joint_state
  - /ascender_joint_state

zed2:
  - /zed/zed_node/atm_press
  - /zed/zed_node/depth/depth_registered
  - /zed/zed_node/imu/data
  - /zed/zed_node/odom
  - /zed/zed_node/left/image_rect_color/compressed
  - /zed/zed_node/right/image_rect_color/compressed
  - /zed/zed_node/point_cloud/cloud_registered

zed2i:
  - /zed/zed_node/atm_press
  - /zed/zed_node/depth/depth_registered
  - /zed/zed_node/imu/data
  - /zed/zed_node/odom
  - /zed/zed_node/left/image_rect_color
  - /zed/zed_node/right/image_rect_color
  - /zed/zed_node/point_cloud/cloud_registered
